# Generated by Django 2.2 on 2020-04-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200407_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
