# Generated by Django 2.2 on 2020-04-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200407_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
