# Generated by Django 2.2 on 2020-04-15 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0012_auto_20200415_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ratedUsers',
            field=models.ManyToManyField(blank=True, related_name='ratedUsersAnswer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpost',
            name='ratedUsers',
            field=models.ManyToManyField(blank=True, related_name='ratedUsersPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
