# Generated by Django 2.2 on 2020-04-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20200415_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ratedUsers',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='forum.Author'),
        ),
    ]
