# Generated by Django 2.2 on 2020-04-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20200415_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='ratedUsers',
        ),
    ]
