# Generated by Django 2.2 on 2020-06-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20200609_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.UserPost'),
        ),
    ]
