# Generated by Django 2.2 on 2020-06-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_topicview'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='I am a Doctor'),
        ),
    ]
