# Generated by Django 2.2 on 2020-06-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_remove_author_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_doctor',
            field=models.BooleanField(blank=True, null=True, verbose_name='I am a Doctor'),
        ),
    ]
