# Generated by Django 2.2 on 2020-06-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_author_is_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_doctor',
            field=models.BooleanField(null=True, verbose_name='I am a Doctor'),
        ),
    ]
