# Generated by Django 2.2 on 2020-06-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_remove_author_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
