# Generated by Django 2.2 on 2020-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_author_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.AddField(
            model_name='author',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True, verbose_name='phone number'),
        ),
    ]
