# Generated by Django 2.2 on 2020-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, default='header.jpg', null=True, upload_to=''),
        ),
    ]
